name: deploy

on:
  push:
    branches:
      - main
  schedule:
      - cron: '0 4 1 * *'      
      
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.APP_NAME }} 
          heroku_email: ${{secrets.EMAIL}}
          usedocker: true
          region: "us"
        env:
          HD_UUID: ${{ secrets.HEROKU_V2RAY_UUID }}
          NODE_ENV: production
          SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
          
  heroku-deploy-2:
    runs-on: ubuntu-latest
    environment: makemefel
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.APP_NAME }} 
          heroku_email: ${{secrets.EMAIL}}
          usedocker: true
          region: "eu"
        env:
          HD_UUID: ${{ secrets.HEROKU_V2RAY_UUID }}
          NODE_ENV: production
          SECRET_KEY: ${{ secrets.MY_SECRET_KEY }} 